### ISSUE TITLE
deprecated? what happen???

### ISSUE THREAD

**Issue by CoolLKKPS** [NicholasScott1337/RuntimeNetcodeRPCValidator#5]
@wwwDayDream this mod are still useful, what happen is anything wrong?

**Comment by Alpen1** [comment]
Came here to ask this as well. Dont see any updates from Author

**Comment by wwwDayDream** [comment]
It can be forked but it's got a few under-the-hood serialization issues and is in a state where it needs a good rework.

Some of the issues are unsupported NGO features and some are just issues where the codebase needs expanded substantially to be inline with NGO feature-set. All in all, it's much easier to use a compile-time NGO patcher that will patch your mod before shipping to users. It's a nifty project and a cool idea to patch mods networking with MonoMod/HarmonyX and I really enjoy(ed) working on it but finals this semester are taking up a bit too much of my time to really delve deep into edge-cases and NGO decompiled code.

Anyone is welcome to fork/continue the project (the license allows adaptations w/ contribution) and I'd recommend it if it piques your interest because I enjoyed working with NGO & Harmony! <3

Edit: [Here's the alternative solution that even has an MSBuild option!](https://github.com/EvaisaDev/UnityNetcodePatcher)
